panel_iframe:
  portainer:
    title: Portainer
    icon: mdi:docker
    url: !secret portainer_url
  grafana:
    title: Grafana
    icon: mdi:chart-timeline
    url: !secret grafana_url
  influxdb:
    title: InfluxDB
    icon: mdi:database
    url: !secret influxdb_url
    
# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

# Text to speech
tts:
  - platform: google_translate

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

influxdb:
  api_version: 2
  ssl: false # Can omit this if using https.
  host: !secret influxdb_host
  port: !secret influxdb_port
  token: !secret influxdb_token
  organization: !secret influxdb_org
  bucket: !secret influxdb_bucket