version: '3.8'

networks:
  front-network:
    name: front-network
  back-network:
    name: back-network

services:
  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto
    volumes:
      - ./mosquitto-data/mosquitto:/mosquitto
      - ./mosquitto-data/mosquitto/data:/mosquitto/data
      - ./mosquitto-data/mosquitto/log:/mosquitto/log
    ports:
      - 1883:1883
      - 9001:9001
    networks:
      front-network:
        ipv4_address: 172.21.0.5
      back-network:
        ipv4_address: 172.22.0.5