version: '3.8'

networks:
  front-network:
    name: front-network
  back-network:
    name: back-network

services:
  influxdb:
    container_name: influxdb
    restart: always
    image: influxdb:latest
    ports:
      - 8086:8086
    volumes:
      - ./influxdb-data/var/lib/influxdb:/var/lib/influxdb
    networks:
      front-network:
        ipv4_address: 172.21.0.3
      back-network:
        ipv4_address: 172.22.0.3